### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by LindaLawton** [SwedbankPay/developer.swedbankpay.com#372]
[payment-order-capture.md](https://github.com/SwedbankPay/developer.swedbankpay.com/blob/a2035a9f7b2bb2a44a14f7527e901af2faa49378/_includes/payment-order-capture.md)

the links for Swis, Vipps and Credit Card dont work.

**Comment by asbjornu** [comment]
Thank you for your report, @LindaLawton. We'll look into this and provide a fix ASAP.

**Comment by LindaLawton** [comment]
I would also like to suggest you do a global search on the term "she" documentation should be gender neutral you have several places with instances of 

>so that **she** can enter the required information in a secure Swedbank

**Comment by asbjornu** [comment]
Thanks for the suggestion. I agree that we can use "the payer" in this situation. We'll go through and change where appropriate.
