### ISSUE TITLE
subsite documentation is a bit vauge

### ISSUE THREAD

**Issue by softarn** [SwedbankPay/developer.swedbankpay.com#690]
Current documentation for subsite

> The subsite field can be used to perform split settlement on the payment. The subsites must be resolved with Swedbank Pay reconciliation before being used.

It's unclear what will happen with a request that contains a subsite that can't be resolved, will it be silently ignored or will this generate an error?

Would appreciate adding `Subsites that can't be resolved will silently be ignored` or similar if that is the case.

**Comment by asbjornu** [comment]
Thanks for reporting this. Unknown values will just be ignored. We will clarify this in the documentation.
